### PR TITLE
#333: Fixed an issue, where Bluetooth would crash the iOS app. This f…

### LINKED ISSUE #333: iOS: BluetoothController freezes app
Repro steps:

New install of more on phone -> login pair polar device -> restart app --> connect to device --> Ui freeze, background processes running

Something is blocking ui thread

### PR DESCRIPTION
**Pull request by janoliver20**
…ix includes multiple changes:

- Moved all necessary states into one single object
- Changed necessary coroutines to run on the default thread queue, as this is runs much faster and better on iOS
- Changed the Bluetooth Controller completely to dynamically react to different states and turn on/off (foreground/background) scans
- Changed the Shared class, to better react to study state, credentials and foreground states to not call the bluetooth controller multiple times and improve reactions

### CODE REVIEW

File: shared/src/commonMain/kotlin/io/redlink/more/more_app_mutliplatform/Shared.kt [hunk 1]
```diff
@@ -264,10 +222,9 @@ class Shared(
                     repositories.notification.deleteAll()
                     ViewManager.studyError(false)
                     repositories.study.upsert(study)
-                    if (study.studyState?.let { StudyState.getState(it) } == StudyState.ACTIVE) {
-                        resetFirstStartUp()
-                        observationFactory.updateObservationErrors()
-                    }
+//                    if (study.studyState?.let { StudyState.getState(it) }?.isActive() == true) {
```
Comment (markus-ebner) [inline shared/src/commonMain/kotlin/io/redlink/more/more_app_mutliplatform/Shared.kt]: delete comment?

**Review by markus-ebner — APPROVED** [review]

**Review by Gmasek — APPROVED** [review]
